const Venue  = require('../models/Venue');

const venueData = [
  {
    "title": "Marriot Hotel",
    "description": "Marriott International, Inc. is an American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties. It is headquartered in Bethesda, Maryland.",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price":899.9,
    "capacity": 550,
    "location": "Fremont",
    "address": "46100 Landing Pkwy, Fremont, CA 94538-6437",
    "phone_number": 5101234567
  },
  {
    "title": "Dave and Buster",
    "description": "Dave & Buster's is an American restaurant and entertainment business headquartered in Dallas. Each Dave & Buster's has a full-service restaurant and a video arcade. As of September 2021, the company has 143 locations in the United States and Canada",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price":499.9,
    "capacity": 100,
    "location": "Milpitas",
    "address": "940 Great Mall Dr, Milpitas, CA 95035",
    "phone_number": 5101234567
  },
  {
    "title": "Chuck e Cheesel",
    "description": "Chuck E. Cheese is an American family entertainment center and restaurant pizza chain founded in 1977 by Atari co-founder Nolan Bushnell. Headquartered in Irving, Texas, each location features arcade games, amusement rides, and animatronic stage shows in addition to serving pizza and other food items",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price":400,
    "capacity": 40,
    "location": "Newark",
    "address": "39839 Mowry School Rd, Newark, CA 94560",
    "phone_number": 5103654132
  },
  {
    "title": "Sala Thai Restaurant",
    "description": "Marriott International, Inc. is an American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties. It is headquartered in Bethesda, Maryland.",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price":200.9,
    "capacity": 30,
    "location": "Fremont",
    "address": "39170 State St, Fremont, CA 94538-1436",
    "phone_number": 5101234567
  },
  {
    "title": "Hyaat Regency Hotel",
    "description": "Meet Hyatt Thrive, our corporate social responsibility platform. Our purpose of care defines our practice of responsibility. By building strong communities and fostering sustainable practices, we’re working to create an environment in which people thrive. As the Hyatt footprint expands to meet the needs of a more connected and traveled world, we have the opportunity—and the responsibility—to grow with purpose and to protect our environment for generations to come. ",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price":899.9,
    "capacity": 550,
    "location": "San Francisco",
    "address": "5 Embarcadero Center, San Francisco, CA 94111",
    "phone_number": 5101234567
  },
  {
    "title": "Levi's Satdium",
    "description": "Levi's Stadium is an American football stadium located in Santa Clara, California, just outside San Jose in the San Francisco Bay Area. It has served as the home venue for the National Football League's San Francisco 49ers since 2014.",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price":1000.999,
    "capacity": 900,
    "location": "Santa Clara",
    "address": "4900 Marie P DeBartolo Way, Santa Clara, CA 95054",
    "phone_number": 5101234567
  },
  {
    "title": "Greenwood Park",
    "description": "Greenwood Park is an excellent little park nestled away in a newer development.  It's the type of park that might make you say, Hey I should move to THIS part of Hayward!  Jokingaside, I was impressed with the park for several reasons.  First, it's very well kept and modern.  There are clean bathrooms, modern kids' play structures, and a basketball court.  The play structures were interesting; they included a climbing wall, musical-hands-on type, and a mound/hill to slide down.  Also, there are plenty of shady spots to sit and have lunch; some of the tables have special tops for playing chess or checkers.  I noticed that the basketball courts and some of the grassy areas were possibly on uneven ground due to the water pooling there.  Another good thing about this park is the ample parking and safe vibe of the neighborhood.  There's no major street nearby and lots of friendly locals around walking",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price":150.9,
    "capacity":50,
    "location": "Hayward",
    "address": "Eden Ave & Middle Ln Hayward, CA 94545",
    "phone_number": 510881700
  },
  {
    "title": "Marriot Hotel",
    "description": "Marriott International, Inc. is an American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties. It is headquartered in Bethesda, Maryland.",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price":899.9,
    "capacity": 550,
    "location": "Santa Clara",
    "address": "786 Great America Parkway, Santa Clare, CA 94556",
    "phone_number": 5101234567
  },
  {
    "title": "Hilton San Fransico",
    "description": " Lorem Ipsum, sometimes referred to as 'lipsum', is the placeholder text used in design when creating content. It helps designers plan out where the content will sit, without needing to wait for the content to be written and approved. It originally comes from a Latin text, but to today's reader, it's seen as gibberish.",
    "main_image_url": "",
    "image_url_1": "",
    "image_url_2": "",
    "image_url_3": "",
    "website": "",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price":900.9,
    "capacity": 650,
    "location": "San Francisco",
    "address": "750 Kearny St San Francisco, CA 94108",
    "phone_number": 5101234567
  }
  
];

const seedVenue = () => Venue.bulkCreate(venueData);

module.exports = seedVenue;