
const Venue = require('../models/Venue');
const venueData = [
  {
    "title": "Marriott Hotel",
    "description": "Marriott International, Inc. is an American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties. It is headquartered in Bethesda, Maryland.",
    "main_image_url": "",
    "website": "www.marriot.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 899,
    "capacity": 550,
    "location": "Fremont",
    "address": "46100 Landing Pkwy, Fremont, CA 94538-6437",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Dave and Buster",
    "description": "Dave & Buster's is an American restaurant and entertainment business headquartered in Dallas. Each Dave & Buster's has a full-service restaurant and a video arcade. As of September 2021, the company has 143 locations in the United States and Canada",
    "main_image_url": "",
    "website": "www.daveandbuster.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "3",
    "price": 499,
    "capacity": 50,
    "location": "Milpitas",
    "address": "940 Great Mall Dr, Milpitas, CA 95035",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Chuck e Cheesel",
    "description": "Chuck E. Cheese is an American family entertainment center and restaurant pizza chain founded in 1977 by Atari co-founder Nolan Bushnell. Headquartered in Irving, Texas, each location features arcade games, amusement rides, and animatronic stage shows in addition to serving pizza and other food items",
    "main_image_url": "",
    "website": "www.chuckecheese.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price": 400,
    "capacity": 40,
    "location": "Newark",
    "address": "39839 Mowry School Rd, Newark, CA 94560",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Sala Thai Restaurant",
    "description": "Marriott International, Inc. is an American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties. It is headquartered in Bethesda, Maryland.",
    "main_image_url": "",
    "website": "www.salathai.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price": 200,
    "capacity": 30,
    "location": "Fremont",
    "address": "39170 State St, Fremont, CA 94538-1436",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Hyaat Regency Hotel",
    "description": "Meet Hyatt Thrive, our corporate social responsibility platform. Our purpose of care defines our practice of responsibility. By building strong communities and fostering sustainable practices, we’re working to create an environment in which people thrive. As the Hyatt footprint expands to meet the needs of a more connected and traveled world, we have the opportunity—and the responsibility—to grow with purpose and to protect our environment for generations to come. ",
    "main_image_url": "",
    "website": "www.hyaatregency.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price": 899,
    "capacity": 250,
    "location": "Pleasanton",
    "address": "5 Embarcadero Center, Pleasanton, CA 94111",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Levi's Satdium",
    "description": "Levi's Stadium is an American football stadium located in Santa Clara, California, just outside San Jose in the San Francisco Bay Area. It has served as the home venue for the National Football League's San Francisco 49ers since 2014.",
    "main_image_url": "",
    "website": "www.levisstadium.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 1000,
    "capacity": 900,
    "location": "Oakland",
    "address": "4900 Marie P DeBartolo Way, Oakland, CA 95054",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Greenwood Park",
    "description": "Greenwood Park is an excellent little park nestled away in a newer development.  It's the type of park that might make you say, Hey I should move to THIS part of Hayward!  Jokingaside, I was impressed with the park for several reasons.  First, it's very well kept and modern.  There are clean bathrooms, modern kids' play structures, and a basketball court.  The play structures were interesting; they included a climbing wall, musical-hands-on type, and a mound/hill to slide down.  Also, there are plenty of shady spots to sit and have lunch; some of the tables have special tops for playing chess or checkers.  I noticed that the basketball courts and some of the grassy areas were possibly on uneven ground due to the water pooling there.  Another good thing about this park is the ample parking and safe vibe of the neighborhood.  There's no major street nearby and lots of friendly locals around walking",
    "main_image_url": "",
    "website": "www.gardenwood.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 150,
    "capacity": 50,
    "location": "Hayward",
    "address": "Eden Ave & Middle Ln Hayward, CA 94545",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Marriot Hotel Milpitas",
    "description": "Marriott International, Inc. is an American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties. It is headquartered in Bethesda, Maryland.",
    "main_image_url": "",
    "website": "www.marriothotelmilpitas.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 899,
    "capacity": 550,
    "location": "Plesanton",
    "address": "786 Great America Parkway,Pleasanton, CA 94556",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Hilton Grant Palace",
    "description": " Lorem Ipsum, sometimes referred to as 'lipsum', is the placeholder text used in design when creating content. It helps designers plan out where the content will sit, without needing to wait for the content to be written and approved. It originally comes from a Latin text, but to today's reader, it's seen as gibberish.",
    "main_image_url": "",
    "website": "www.hilton.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 900.,
    "capacity": 750,
    "location": "Berkeley",
    "address": "750 Kearny St Berekely, CA 94108",
    "phone_number": "510-354-1234"
  },
  {
    "title": "The Ranch At Silver Creek",
    "description": "Mediterranean escape that provides exceptional views. Wedding ceremonies overlooking the rolling hills create a charming scenic backdrop! Receptions in our contemporary and elegantly appointed ballroom with tray ceilings, stone accents, a cozy fireplace, and city skyline views will create memories to last a lifetime!",
    "main_image_url": "",
    "website": "http://theranchatsilvercreek.com/",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 200,
    "capacity": 250,
    "location": "Berkeley",
    "address": "4601 Hill Top View Lane, Berkeley, California 95138",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Presidio",
    "description": "The park is home to eight scenic overlooks with spectacular views of the bridge, the bay, the ocean, and the Presidio forest. Overlooks are located along the Presidio trail system​.​​​​​​​​​​​​​​​​​​​​​​​​​​​​​",
    "main_image_url": "",
    "website": "www.presidio.gov",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "2",
    "price": 5000,
    "capacity": 300,
    "location": "Richmond",
    "address": "135 Fisher Loop, Richmond, CA 94129",
    "phone_number": "510-354-1234"
  },
  {
    "title": 'Sterling Hotel',
    "description": "The refined Victorian design features architectural amusements like an artisanal stained-glass dome, a cellar bar, and an adorable chapel​.​​​​​​​​​​​​​​​​​​​​​​​​​​​​​",
    "main_image_url": "",
    "website": "www.sterlinginnsc.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 1000,
    "capacity": 200,
    "location": "Sacramento",
    "address": "1300 H St, Sacramento, CA 95814",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Ocotillo Oasis",
    "description": "This romantic and lush venue will entice you everywhere you look with delightful photo opportunities - from the sparkling lakes to the rolling greens.​​​​​​​​​​​​​​​​​​​​​​​​​",
    "main_image_url": "",
    "website": "https://www.instagram.com/wedgewood.ocotillo/?hl=en",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "3",
    "price": 7000,
    "capacity": 200,
    "location": "Milpitas",
    "address": "3751 S Clubhouse Drive, Milpitas, AZ 85248",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Aliso Viejo Country Club",
    "description": "A sanctuary for laid back-yet-savvy couples, the views across to Saddleback Mountain are picture perfect and provide a serene backdrop that is naturally-stunning.",
    "main_image_url": "",
    "website": "https://avcity.org/",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "3",
    "price": 15,
    "capacity": 280,
    "location": "Richmond",
    "address": "31 Santa Barbara Dr, Richmond, CA 92656",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Toll House Hotel",
    "description": "Nestled in the lively downtown, this hotel combines down - to - earth decor and naturesque views with contemporary details",
    "main_image_url": "",
    "website": "www.tollhousehotel.com",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 9000,
    "capacity": 300,
    "location": "Sacramento",
    "address": "140 South Santa Cruz Avenue,Sacramento, CA",
    "phone_number": "510-354-1234"
  },
  {
    "title": "The Pinery at The Hill",
    "description": "The Pinery at The Hill is a resort - style wedding and event venue.The management of this stunning locale welcomes to - be - weds that are seeking a suitable backdrop for their nuptials, with architecture reminiscent of Tuscany in Italy.",
    "main_image_url": "",
    "website": "https://www.instagram.com/thepineryatthehill/",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price": 2000,
    "capacity": 400,
    "location": "Berkeley",
    "address": "775 West Bijou Street, Berkeley , CA",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Emerald at Queensridge",
    "description": "Emerald at Queensridge was designed and built exclusively for the perfect wedding and reception.Whether you are a local or an out of towner, we guarantee you the wedding you have always dreamed about.",
    "main_image_url": "",
    "website": "https://www.emeraldatqueensridge.com/",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "5",
    "price": 1000,
    "capacity": 500,
    "location": "Oakland",
    "address": "891 S Rampart Blvd,Oakland, CA",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Zion Red Rock",
    "description": "The Zion Red Rock Oasis is a spacious, 14, 000 sq ft multi million dollar luxurious mansion nestled on 15 acres of beautiful land.This mansion wedding venue serves as an ideal location for the adventurous couples.",
    "main_image_url": "",
    "website": "https://https://www.zionredrock.com/",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "3",
    "price": 1000,
    "capacity": 175,
    "location": "Sacramento",
    "address": "955 West 250 South, Sacramento, CA",
    "phone_number": "510-354-1234"
  },
  {
    "title": "Hyatt Regency Maui Resort & Spa",
    "description": "Set on 40 acres on Ka’anapali Beach, the completely - reimagined Hyatt Regency Maui Resort and Spa is a getaway in paradise.",
    "main_image_url": "",
    "website": "www.hyatt.com/en-US/hotel/hawaii/hyatt-regency-maui-resort-and-spa",
    "category": ["Wedding", "Birthday", "Exhibition", "Concert", "Conference"].toString(),
    "rating": "4",
    "price": 900,
    "capacity": 400,
    "location": "Pleasanton",
    "address": "200 Nohea Kai Drive, Pleasanton, CA",
    "phone_number": "510-354-1234"
  }
];

const seedVenue = () => Venue.bulkCreate(venueData);
module.exports = seedVenue;

